import os
import argparse
import sys
import math
from pathlib import Path

import torch
import torch.nn.functional as F
import torchvision.io
from tqdm import tqdm
from datasets import load_dataset

# Add wan_va and its parent to path so we can import modules
sys.path.append(os.path.dirname(os.path.abspath(__file__)))
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from modules.utils import load_vae, load_text_encoder, load_tokenizer, WanVAEStreamingWrapper

def get_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--dataset_path", type=str, required=True, help="Path to LeRobot dataset")
    parser.add_argument("--ckpt_path", type=str, default="./ckpt/lingbot-va-base", help="Path to Wan-VA models")
    parser.add_argument("--chunk_size", type=int, default=2, help="VAE chunk size (num frames to encode at once)")
    parser.add_argument("--height", type=int, default=256, help="Target height for latents")
    parser.add_argument("--width", type=int, default=320, help="Target width for latents")
    parser.add_argument("--shard_id", type=int, default=0, help="Shard ID for parallel extraction (0 to num_shards-1)")
    parser.add_argument("--num_shards", type=int, default=1, help="Total number of shards for parallel extraction")
    return parser.parse_args()

def normalize_latents(latents, mean, std):
    return (latents - mean) * std

@torch.no_grad()
def main():
    args = get_args()
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    dtype = torch.bfloat16
    
    print(f"Loading VAE from {args.ckpt_path}/vae on {device}...")
    vae = load_vae(os.path.join(args.ckpt_path, "vae"), dtype, device)
    streaming_vae = WanVAEStreamingWrapper(vae)
    latents_mean = torch.tensor(vae.config.latents_mean).to(device).view(1, -1, 1, 1, 1)
    latents_std = torch.tensor(vae.config.latents_std).to(device).view(1, -1, 1, 1, 1)

    print(f"Loading Text Encoder and Tokenizer from {args.ckpt_path}...")
    text_encoder = load_text_encoder(os.path.join(args.ckpt_path, "text_encoder"), dtype, device)
    tokenizer = load_tokenizer(os.path.join(args.ckpt_path, "tokenizer"))
    
    # Pre-tokenize defaults
    text_len = 512
    print(f"Loading Episodes Metadata from {args.dataset_path}...")
    ep_map = {}
    
    meta_dir = os.path.join(args.dataset_path, "meta")
    print(f"Contents of {meta_dir} on server:")
    if os.path.exists(meta_dir):
        for root, dirs, files in os.walk(meta_dir):
            for file in files:
                print("  -", os.path.join(root, file))
    else:
        print(f"  [ERROR] {meta_dir} DOES NOT EXIST!")

    # Try pure python JSONL parsing first, because this dataset was generated by a script that writes episodes.jsonl
    jsonl_path = os.path.join(args.dataset_path, "meta", "episodes.jsonl")
    if os.path.exists(jsonl_path):
        import json
        with open(jsonl_path, 'r') as f:
            for line in f:
                if not line.strip(): continue
                item = json.loads(line)
                ep_map[item["episode_index"]] = item
    else:
        # Fallback to parquet
        try:
            import glob
            parquet_files = glob.glob(os.path.join(args.dataset_path, "meta", "episodes", "**", "*.parquet"), recursive=True)
            if len(parquet_files) == 0:
                print("No parquet files found in meta/episodes directory!")
                return
            episode_ds = load_dataset("parquet", data_files=parquet_files, split="train")
            for item in episode_ds:
                ep_map[item["episode_index"]] = item
        except Exception as e:
            print(f"Failed to load episodes via both JSONL and Parquet! Error: {e}")
            return

    if len(ep_map) == 0:
        print("No metadata parsed, exiting.")
        return

    # We use natively LeRobotDataset to abstract away the chunked video decodings!
    from lerobot.datasets.lerobot_dataset import LeRobotDataset
    print("Initializing LeRobotDataset to cleanly load frames locally... (this might take a few seconds)")
    try:
        # LeRobotDataset requires root to be the directory that CONTAINS meta/ and videos/, 
        # i.e., exactly args.dataset_path. 
        # We pass a dummy repo_id just so it doesn't complain, but it will load offline from root.
        repo_id = os.path.basename(os.path.normpath(args.dataset_path))
        root_dir = args.dataset_path
        ds = LeRobotDataset(repo_id=repo_id, root=root_dir)
    except Exception as e:
        print(f"Failed to init LeRobotDataset: {e}")
        return

    used_video_keys = [k for k in ds.meta.features if "observation.images" in k or "observation.tactiles" in k]
    if len(used_video_keys) == 0:
        print("No image/tactile keys found in dataset!")
        return

    latents_dir = Path(args.dataset_path) / "latents"

    print(f"Extracting latents for {len(ep_map)} episodes using {len(used_video_keys)} keys ...")
    
    for idx, meta_item in tqdm(ep_map.items(), desc=f"Episodes (Shard {args.shard_id}/{args.num_shards})"):
        if idx % args.num_shards != args.shard_id:
            continue
            
        tasks = meta_item.get("tasks", ["perform the manipulation task"])
        
        action_config = meta_item.get("action_config", [
            {
                "start_frame": 0,
                "end_frame": meta_item["length"],
                "action_text": tasks[0] if isinstance(tasks, list) and len(tasks) > 0 else tasks,
            }
        ])
        
        # Get frame boundaries for this episode in the global dataset view
        try:
            meta_ep = ds.meta.episodes[idx]
            ep_start = meta_ep.get("dataset_from_index", meta_ep.get("from"))
            ep_end = meta_ep.get("dataset_to_index", meta_ep.get("to"))
            if ep_start is None:
                raise ValueError("Missing 'from'/'dataset_from_index'")
        except Exception as e:
            print(f"Skipping episode {idx}: failed to find start index - {e}")
            continue

        # For every segment
        for acfg in action_config:
            start_f = acfg["start_frame"]
            end_f = acfg["end_frame"]
            text = acfg["action_text"]
            if isinstance(text, list): text = text[0]
            
            # Extract Segment for each camera
            for key in used_video_keys:
                try:
                    # In lerobot metadata, the relative path to chunks is usually implicit.
                    # We need to construct output path based on index / chunk logic.
                    episode_chunk = meta_item.get("meta/episodes/chunk_index", idx // 1000)
                    cur_path = latents_dir / f"chunk-{episode_chunk:03d}" / key
                    cur_path.mkdir(parents=True, exist_ok=True)
                    out_path = cur_path / f"episode_{idx:06d}_{start_f}_{end_f}.pth"
                    
                    if out_path.exists():
                        continue
                        
                    # Preload all frames for this single segment sequentially using LeRobot
                    # This gracefully handles `file-000.mp4` seeking in the background.
                    # Note: we need to handle start/end properly based on ep_start
                    global_frame_indices = range(ep_start + start_f, ep_start + end_f)
                    
                    frames = []
                    for gi in global_frame_indices:
                        frame = ds[gi][key] # [C, H, W] in [0.0, 1.0] scale theoretically, or uint8?
                        frames.append(frame)
                    
                    if len(frames) == 0:
                        continue
                        
                    segment = torch.stack(frames) # [T, C, H, W]
                    
                    # Convert lerobot frame standard if it's float [0,1] or uint8 [0,255]
                    if segment.dtype == torch.uint8:
                        segment = segment.float() / 255.0
                    else:
                        segment = segment.float()
                        
                    T_video, C, orig_H, orig_W = segment.shape
                    
                    # Resize -> [T, 3, 256, 320]
                    segment = F.interpolate(segment, size=(args.height, args.width), mode='bilinear', align_corners=False)
                    
                    # Prepare for VAE: [B=1, C=3, F=T, H, W] and scale to [-1, 1]
                    videos_chunk = segment.permute(1, 0, 2, 3).unsqueeze(0)
                    videos_chunk = videos_chunk * 2.0 - 1.0
                    videos_chunk = videos_chunk.to(device).to(dtype)
                    
                    # Bypassing the critically bugged WanVAEStreamingWrapper.
                    # Instead, we rely on standard Diffusers VAE API and batch independently.
                    safe_chunk_size = 80  # safe limit for VRAM
                    
                    pad_T = (safe_chunk_size - (T_video % safe_chunk_size)) % safe_chunk_size
                    if pad_T > 0:
                        videos_chunk = F.pad(videos_chunk, (0, 0, 0, 0, 0, pad_T), mode='replicate')
                    
                    padded_T_video = videos_chunk.shape[2]
                    mu_list = []
                    
                    try:
                        for i in range(0, padded_T_video, safe_chunk_size):
                            vc = videos_chunk[:, :, i:i+safe_chunk_size]
                            # Using native Diffusers API directly
                            dist = vae.encode(vc).latent_dist
                            mu = dist.mean
                            mu_norm = normalize_latents(mu, latents_mean, 1.0 / latents_std)
                            mu_list.append(mu_norm)
                    except Exception as e:
                        print(f"VAE Native Encode Error on block {i}: {e}")
                        raise e
                    
                    video_latent = torch.cat(mu_list, dim=2)
                    
                    # Temporal downsampling relies on VAE config, usually 4.
                    # We compute exact valid latent length:
                    downsample_ratio = safe_chunk_size // mu_list[0].shape[2]
                    valid_F_lat = math.ceil(T_video / downsample_ratio) if downsample_ratio > 0 else mu_list[0].shape[2]
                    video_latent = video_latent[:, :, :valid_F_lat, :, :]
                    B_lat, C_lat, F_lat, H_lat, W_lat = video_latent.shape
                    video_latent_flat = video_latent.squeeze(0).permute(1, 2, 3, 0).reshape(-1, C_lat).cpu()
                    
                    # Encode Text
                    inputs = tokenizer(text, return_tensors='pt', padding='max_length',
                                       max_length=text_len, truncation=True)
                    text_emb = text_encoder(inputs.input_ids.to(device))[0]
                    text_emb = text_emb.squeeze(0).cpu() # [L, D]
                    
                    info_fps = meta_item.get("fps", 10)
                    
                    latent_dict = {
                        "latent": video_latent_flat.to(dtype),
                        "latent_num_frames": F_lat,
                        "latent_height": H_lat,
                        "latent_width": W_lat,
                        "video_num_frames": T_video,
                        "video_height": args.height,
                        "video_width": args.width,
                        "text_emb": text_emb.to(dtype),
                        "text": text,
                        "frame_ids": list(range(start_f, end_f)),
                        "start_frame": start_f,
                        "end_frame": end_f,
                        "fps": info_fps,
                        "ori_fps": info_fps
                    }
                    
                    torch.save(latent_dict, out_path)
                
                except Exception as e:
                    print(f"Error encoding {key} episode {idx}: {e}")

    print("Extraction complete!")
    total_generated = list(latents_dir.rglob("*.pth"))
    print(f"\n[DEBUG] Total .pth files found in latents directory: {len(total_generated)}")
    if len(total_generated) > 0:
        print(f"[DEBUG] Sample .pth file paths:")
        for f in total_generated[:10]:
            print(f"  - {f}")
    else:
        print(f"[ERROR] ABSOLUTELY NO .pth FILES WERE GENERATED!")

if __name__ == "__main__":
    main()
