#!/bin/bash
if [[ "$*" == *"-p"* ]]; then
    /sbin/ldconfig -p 2>/dev/null
    echo "	libnvrtc.so.11.2 (libc6,x86-64) => $NVRTC_PATH"
    echo "	libnvrtc.so.12 (libc6,x86-64) => $NVRTC_PATH"
    echo "	libnvrtc.so (libc6,x86-64) => $NVRTC_PATH"
    exit 0
fi
/sbin/ldconfig "$@"
